# Generated by Django 6.0.1 on 2026-01-15 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScoreFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weight', models.FloatField(help_text='Importance weight in scoring')),
                ('impact', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_type', models.CharField(max_length=50)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('roc_auc', models.FloatField()),
                ('parameters', models.JSONField()),
                ('feature_importance', models.JSONField(blank=True, null=True)),
                ('model_file', models.FileField(upload_to='models/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('prediction', 'Prediction Made'), ('model_training', 'Model Training'), ('application_submission', 'Application Submission'), ('decision_made', 'Decision Made'), ('system_change', 'System Change')], max_length=50)),
                ('details', models.JSONField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('age', models.IntegerField()),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employment_status', models.CharField(max_length=50)),
                ('employment_duration', models.IntegerField(help_text='In months')),
                ('education_level', models.CharField(max_length=50)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('number_of_credit_lines', models.IntegerField()),
                ('credit_card_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_card_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_utilization_ratio', models.FloatField(blank=True, null=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_purpose', models.CharField(max_length=200)),
                ('loan_term_months', models.IntegerField()),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('late_payments_90days', models.IntegerField(default=0)),
                ('late_payments_60days', models.IntegerField(default=0)),
                ('late_payments_30days', models.IntegerField(default=0)),
                ('prediction_score', models.FloatField(blank=True, null=True)),
                ('predicted_credit_rating', models.CharField(blank=True, choices=[('A+', 'Excellent (A+)'), ('A', 'Very Good (A)'), ('B', 'Good (B)'), ('C', 'Fair (C)'), ('D', 'Poor (D)'), ('E', 'Very Poor (E)')], max_length=10, null=True)),
                ('predicted_status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('under_review', 'Under Review')], default='pending', max_length=20)),
                ('debt_to_income_ratio', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('final_decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('under_review', 'Under Review')], max_length=20, null=True)),
                ('final_credit_rating', models.CharField(blank=True, choices=[('A+', 'Excellent (A+)'), ('A', 'Very Good (A)'), ('B', 'Good (B)'), ('C', 'Fair (C)'), ('D', 'Poor (D)'), ('E', 'Very Poor (E)')], max_length=10, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
