# Generated by Django 6.0.1 on 2026-01-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditapplication',
            old_name='applicant',
            new_name='user',
        ),
    ]
