# Generated by Django 6.0.1 on 2026-01-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0002_rename_applicant_creditapplication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='employment_duration',
            field=models.IntegerField(default=0, help_text='In months'),
        ),
    ]
